//go:build !ignore_autogenerated

/*
Copyright 2024 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailingClaim) DeepCopyInto(out *FailingClaim) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailingClaim.
func (in *FailingClaim) DeepCopy() *FailingClaim {
	if in == nil {
		return nil
	}
	out := new(FailingClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchedClaim) DeepCopyInto(out *MatchedClaim) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchedClaim.
func (in *MatchedClaim) DeepCopy() *MatchedClaim {
	if in == nil {
		return nil
	}
	out := new(MatchedClaim)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicy) DeepCopyInto(out *QuotaPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicy.
func (in *QuotaPolicy) DeepCopy() *QuotaPolicy {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuotaPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyList) DeepCopyInto(out *QuotaPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QuotaPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyList.
func (in *QuotaPolicyList) DeepCopy() *QuotaPolicyList {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QuotaPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicySelector) DeepCopyInto(out *QuotaPolicySelector) {
	*out = *in
	if in.PVCName != nil {
		in, out := &in.PVCName, &out.PVCName
		*out = new(string)
		**out = **in
	}
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageClassNames != nil {
		in, out := &in.StorageClassNames, &out.StorageClassNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicySelector.
func (in *QuotaPolicySelector) DeepCopy() *QuotaPolicySelector {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicySpec) DeepCopyInto(out *QuotaPolicySpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.DefaultQuota != nil {
		in, out := &in.DefaultQuota, &out.DefaultQuota
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxQuota != nil {
		in, out := &in.MaxQuota, &out.MaxQuota
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MinQuota != nil {
		in, out := &in.MinQuota, &out.MinQuota
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicySpec.
func (in *QuotaPolicySpec) DeepCopy() *QuotaPolicySpec {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaPolicyStatus) DeepCopyInto(out *QuotaPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FailingClaims != nil {
		in, out := &in.FailingClaims, &out.FailingClaims
		*out = make([]FailingClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DriftedClaims != nil {
		in, out := &in.DriftedClaims, &out.DriftedClaims
		*out = make([]FailingClaim, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MatchedClaimSample != nil {
		in, out := &in.MatchedClaimSample, &out.MatchedClaimSample
		*out = make([]MatchedClaim, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaPolicyStatus.
func (in *QuotaPolicyStatus) DeepCopy() *QuotaPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(QuotaPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
